### Get all users
GET http://localhost:3000/admin/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmIyMjAwZS00ODU3LTRmNDgtYTk5My1mZjBjMjdkNmI4MjkiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzMTEzNzksImV4cCI6MTc1MTM5Nzc3OX0.6duRMEFg383sA5cVzcdSeQkFPdkE2Z9qWEfrzDwNPHw

###  Get a single user by ID
GET http://localhost:3000/admin/user/618b8606-1da4-41f3-9bd0-d2d542724816
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjY5ZGQwNC0wN2JiLTQ1MGMtYjlhNi00MmNmYjNjYWYyYWIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEwNzAxMDcsImV4cCI6MTc1MTE1NjUwN30.YkD5xZxzJqYDy1yDvbyW90gu4yKU3Yo5m_-5-4WQd3k

### Update user’s role
PATCH http://localhost:3000/admin/user/618b8606-1da4-41f3-9bd0-d2d542724816/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjY5ZGQwNC0wN2JiLTQ1MGMtYjlhNi00MmNmYjNjYWYyYWIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEwNzAxMDcsImV4cCI6MTc1MTE1NjUwN30.YkD5xZxzJqYDy1yDvbyW90gu4yKU3Yo5m_-5-4WQd3k

{
    "role": "ADMIN"
}

### Delete a user
DELETE http://localhost:3000/admin/user/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjY5ZGQwNC0wN2JiLTQ1MGMtYjlhNi00MmNmYjNjYWYyYWIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEwNzAxMDcsImV4cCI6MTc1MTE1NjUwN30.YkD5xZxzJqYDy1yDvbyW90gu4yKU3Yo5m_-5-4WQd3k